#!/usr/bin/env node
/**
 * Regenerate docs/ROADMAP.md from docs/roadmap.html.
 *
 * The HTML is the source: its `EPICS` array holds every task, its status, and
 * its PR links. The markdown is a mirror, for reading in the repo and in diffs.
 *
 * This script exists because the two drifted — the HTML was six merged PRs
 * behind the markdown, and neither of them agreed with git. Anything you have
 * to update by hand in three places gets updated in one.
 *
 *   node scripts/gen-roadmap.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'docs/roadmap.html'), 'utf8');

/** Lift the EPICS array straight out of the page — same data, one source. */
function readEpics() {
  const start = html.indexOf('const EPICS = [');
  const end = html.indexOf('\n];', start);
  if (start === -1 || end === -1) throw new Error('EPICS array not found in docs/roadmap.html');
  const body = html.slice(start + 'const EPICS = '.length, end + 2);
  return new Function(`return ${body}`)();
}

const RANK = { p0: 0, p1: 1, p2: 2, p3: 3 };
const epics = readEpics().sort((a, b) => RANK[b.pri] - RANK[a.pri]); // mirror reads low → high

/** Same state machine as the page, so the two can never disagree. */
function state(t) {
  const d = `${t.deps || ''} ${t.scope || ''}`;
  if (t.done) return 'done';
  if (/YOUR|Your |your on-device|awaiting your|Blocked on YOUR/.test(d)) return 'hold';
  if (/In progress|Branch |⏸|Root boundary|Demo badge/.test(d)) return 'now';
  return 'open';
}

/** Same words the page uses, so the two copies never say different things. */
const STATUS = {
  done: (t) => `**Shipped**${prs(t) ? ` (${prs(t)})` : ''}`,
  now: () => 'In progress',
  hold: () => 'Needs you',
  open: () => 'Open',
};

/** "PR #40, #41" — pulled from whatever links the deps line carries. */
function prs(t) {
  const nums = [...(t.deps || '').matchAll(/pull\/(\d+)/g)].map((m) => m[1]);
  if (!nums.length) return (t.deps || '').match(/PRs? #[\d\s+#]+/)?.[0] ?? '';
  return `PR ${nums.map((n) => `#${n}`).join(', ')}`;
}

/**
 * HTML → plain text. Strips the anchors, decodes the entities the page needs to
 * show angle brackets, and squashes the pipes that would otherwise break a
 * markdown table row.
 */
const plain = (s) =>
  (s || '')
    .replace(/<a [^>]*>(.*?)<\/a>/g, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/\|/g, '⎮')
    .trim();

const rows = (epic) =>
  epic.tasks
    .map((t, i) => {
      const what = [plain(t.scope), plain(t.deps) && `*${plain(t.deps)}*`].filter(Boolean).join(' ');
      return `| **${epic.prefix}${i + 1}** | \`${t.id}\` | ${what} | ${t.size} | ${STATUS[state(t)](t)} |`;
    })
    .join('\n');

const header = `# Arrival — Launch Roadmap

<!-- GENERATED by scripts/gen-roadmap.mjs from docs/roadmap.html — do not hand-edit. -->

**The roadmap has three copies, and this is the reading order:**

| Copy | What it's for |
|---|---|
| [\`docs/roadmap.html\`](roadmap.html) | **The source.** The full interactive page — filters, state, PR links, copy-as-issue. Edit the \`EPICS\` array here; everything else is generated from it. |
| The live artifact | The published, shareable view of \`docs/roadmap.html\` (same file, republished in place — the URL never changes). See \`reference-roadmap-artifact\` in project memory. |
| This file | The plain-text mirror, for reading in the repo and in diffs. Run \`node scripts/gen-roadmap.mjs\` after editing the HTML; never hand-edit it. |

Tasks are numbered by epic prefix (D1, V3, B4…). This mirror is ordered
**low → high priority (the bottom ships first)**; the HTML page reorders to
ship-blocking-first, which is the better read. Every task is scoped as one PR.

> **The gate:** do not submit to the App Store before the live backend ships —
> a simulation-only build is a guideline 4.2 (minimal functionality) rejection.
> See \`docs/REVIEW_NOTES.md\`.
`;

const body = epics
  .map(
    (e) => `
## ${e.prefix} — ${e.title} (${e.priLabel})

${e.why}

| # | Slice | What | Size | Status |
|---|---|---|---|---|
${rows(e)}`
  )
  .join('\n');

const counts = epics
  .flatMap((e) => e.tasks)
  .reduce((acc, t) => ({ ...acc, [state(t)]: (acc[state(t)] ?? 0) + 1 }), {});

const footer = `

---

**${counts.done ?? 0} shipped · ${counts.now ?? 0} in progress · ${counts.hold ?? 0} blocked · ${counts.open ?? 0} open.**
`;

writeFileSync(join(root, 'docs/ROADMAP.md'), header + body + footer);
console.log(
  `docs/ROADMAP.md regenerated — ${epics.length} epics, ${epics.flatMap((e) => e.tasks).length} tasks ` +
    `(${counts.done ?? 0} shipped, ${counts.now ?? 0} in progress, ${counts.hold ?? 0} blocked, ${counts.open ?? 0} open)`
);
